"""탐지 튜닝 상수 한곳. 골든 단위 테스트로 검증·튜닝한다."""

WINDOW_DAYS = 28
REEMERGENCE_GAP_MIN = 7

SURPRISAL_MIN_BITS = 2.0
DAILY_DIFFERENCE_LIMIT = 3
MIN_ACTIVE_HISTORY_DAYS = 2
DISMISS_EXCLUDE_COUNT = 3
DISMISS_WINDOW_DAYS = 28
